# Generated by Django 2.1.15 on 2020-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTaskScheduler', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='runtime',
            field=models.FloatField(default=0),
        ),
    ]
