# Generated by Django 2.1.15 on 2020-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTaskScheduler', '0004_log_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
    ]
